name: client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_ui_auth: ^1.16.0
  intl: ^0.19.0
  firebase_core: ^3.9.0
  dio: ^5.7.0
  flutter_markdown: ^0.7.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
